### ISSUE TITLE
With extension enabled, images universally download as .webp

### ISSUE THREAD

**Issue by wynden** [nopperl/load-reddit-images-directly#15]
When this add-on is enabled, all images download in .webp file format, rather than their native format. I don't know if this add-on is somehow prompting it or if it's conflicting with my Firefox add-ons that disable .webp. When this add-on is disabled, the same files download as .jpg or .png.  

This is forcing users to make a choice between dealing with the undesired file extension or the undesired image wrapper on reddit.

**Comment by nopperl** [comment]
Presumably images hosted on reddit are downloaded in .webp format?

If yes, that is because extension forces the default Firefox `Accept` value for images, which includes a preference for .webp (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values). This is done even if other extensions such as [Don't "Accept" image/webp](https://addons.mozilla.org/en-US/firefox/addon/dont-accept-webp/) are installed.

I will add an optional feature to use the older `Accept` value (without .webp) instead.
