### ISSUE TITLE
Stop recommending the current Chrome alternative

### ISSUE THREAD

**Issue by Xyl-AU** [nopperl/load-reddit-images-directly#17]
The Reddit load images directly extension for Chrome has been sold and will likely become spyware as it brings up a popup instructing users to enable extra permissions on the next update.

See https://github.com/MonsterMannen/reddit-load-images-directly-chrome/issues/6.

**Comment by nopperl** [comment]
Thanks for bringing this to my attention @Xyl-AU! I've removed the link for now.

**Comment by Poopooracoocoo** [comment]
Any chance of you releasing a Chrome extension? Or do you know of any Chrome extensions or userscripts?

**Comment by Welding-Torch** [comment]
Thanks @Poopooracoocoo, I've been looking for a replacement. I imagine many other users are also looking for a replacement.

**Comment by nopperl** [comment]
@Poopooracoocoo since I don't have a Chrome developer account, I probably won't maintain a Chrome extension. Thanks for recommending an alternative, but given what happened I am reluctant to put it on the readme for now ^^

**Comment by Poopooracoocoo** [comment]
I'd be happy to spot the $5 one-time registration fee and donate some to support you, if that changes anything?

**Comment by 3ncy** [comment]
Hey, I've been looking for an alternative for chrome and landed on this issue. Since the extension recommended by @Poopooracoocoo is closed-source, I have simply ported this one to work on chromium-based browsers.

### https://github.com/3ncy/load-reddit-images-directly-Chrome

Due to Manifest v2 being deprecated on Chrome web store, I can't publish it, but I have included simple instructions on how you can install it yourself.

**Comment by Welding-Torch** [comment]
@3ncy You're doing amazing work my friend

**Comment by Deleca7755** [comment]
Thank you for converting It for Chromium users

I got the `The 'webRequest' API cannot be used with event pages.` error on Opera GX which wouldn't let me Install It. Fixed It by changing `persistent` to `true` In the `manifest.json`, In case anyone else has the Issue
