### ISSUE TITLE
The extension in Firefox is not working.

### ISSUE THREAD

**Issue by toxicprocyon** [nopperl/load-reddit-images-directly#7]
![Screenshot 2024-02-10 220536](https://github.com/nopperl/load-reddit-images-directly/assets/3154099/7259053d-9688-4839-bc73-39c867f383c8)

**Comment by nopperl** [comment]
For which URL did this occur?

**Comment by KaizenNeko** [comment]
Since the OP hasn't replied, I'll provide one.

Reddit Link:
https://preview.redd.it/does-anyone-know-whats-wrong-with-my-cat-v0-gkl213q16cjc1.jpeg?width=1399&format=pjpg&auto=webp&s=a31e4fbb9dc6480785a260ea7bbcaff2d8ef9675

The actual image loads for a split second before the 403 page loads.

Redirected Link:
https://i.redd.it/does-anyone-know-whats-wrong-with-my-cat-v0-gkl213q16cjc1.jpeg

**Comment by nopperl** [comment]
I can't really reproduce your example, the preview.redd.it URL works both with the i.redd.it redirect enabled and disabled. https://i.redd.it/does-anyone-know-whats-wrong-with-my-cat-v0-gkl213q16cjc1.jpeg returns a 403, but this is known, as it needs the URL parameters to work (i.e., https://i.redd.it/does-anyone-know-whats-wrong-with-my-cat-v0-gkl213q16cjc1.jpeg?width=1399&format=pjpg&auto=webp&s=a31e4fbb9dc6480785a260ea7bbcaff2d8ef9675). Even if the i.redd.it redirect is enabled, the extension redirects to the latter URL, so I'm not sure where you get the error.

**Comment by KaizenNeko** [comment]
I just found the culprit in my case. It was a Greasy Fork script called _[Resize Image On "Open image in new tab"](https://greasyfork.org/en/scripts/2312-resize-image-on-open-image-in-new-tab)_. It was stripping out the parameters and redirecting to i.redd.it. It's no longer maintained so I'm just going to comment out the reddit part myself.

**Comment by Tiagoquix** [comment]
@nopperl Hi, I believe this can be closed since the extension was not the culprit.
